export const ENTITY_SEEDS = [
  {
    id: "self",
    name: "使用者本人",
    type: "individual",
    gstRegistered: false,
    basCycle: "none",
    sortOrder: 1,
    active: true,
  },
  {
    id: "spouse",
    name: "配偶",
    type: "individual",
    gstRegistered: false,
    basCycle: "none",
    sortOrder: 2,
    active: true,
  },
  {
    id: "boyun_trust",
    name: "Boyun Trust",
    type: "trust",
    gstRegistered: false,
    basCycle: "none",
    sortOrder: 3,
    active: true,
  },
  {
    id: "boyun_co",
    name: "Boyun Pty Ltd",
    type: "company",
    gstRegistered: true,
    basCycle: "quarterly",
    sortOrder: 4,
    active: true,
  },
  {
    id: "yeeliving_co",
    name: "Yeeliving Pty Ltd（易居）",
    type: "company",
    gstRegistered: true,
    basCycle: "quarterly",
    sortOrder: 5,
    active: true,
  },
  {
    id: "neighbourhood_co",
    name: "Neighbourhood Project Pty Ltd",
    type: "company",
    gstRegistered: true,
    basCycle: "quarterly",
    sortOrder: 6,
    active: true,
  },
] as const;

export const LICENCE_SEED = {
  holder: "self",
  type: "estate_agent",
  regulator: "BLA / CAV",
  portalUrl: "https://my.consumer.vic.gov.au",
  lodgementWindowWeeks: 6,
} as const;
